### PR TITLE
list of minimizer

### PR DESCRIPTION
**Pull request by alexander-akait**

### CODE REVIEW

**Review by michael-ciniawsky — APPROVED** [review]

**Comment by michael-ciniawsky** [comment]
We should/could maybe extend it to non-js minimizers aswell e.g `cssnano-webpack-plugin`. It's a separate issue I know but I don't know where to open/put it :)

**Comment by alexander-akait** [comment]
@michael-ciniawsky before we don't implement built-in support css, it is out of scope of this. BTW I am the leader `cssnano` repo and in my plans implement `cssnano-webpack-plugin` in near future (inside `cssnano repo`, it is monorep).

**Comment by michael-ciniawsky** [comment]
> before we don't implement built-in support css, it is out of scope of this

Do we need to really have to have native module support before promoting a 'official'  minimizer for other **`asset`** types ?. I'm ok with that, but don't think it is a requirement. 

> BTW I am the leader cssnano repo and in my plans implement cssnano-webpack-plugin in near future (inside cssnano repo, it is monorep).

I know :) (watching the repo) and fine with that solution just wanted to mention that support for minification of other asset types is also very important (The JS only focus will be a long-term concern for `webpack` compared to other bundlers like e.g `parcel`)

**Comment by alexander-akait** [comment]
> Do we need to really have to have native module support before promoting a 'official' minimizer for other asset types ?. I'm ok with that, but don't think it is a requirement.

We can implement `CssnanoWebpackPlugin` and provide his as official recommended minimizer for css :smile:

**Comment by sokra** [comment]
Thanks

**Pull request merged**
